image: gradle:jdk11

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

package:
  stage: build
  script:
    - export SPRING_PROFILES_ACTIVE=dev
    - ./gradlew assemble -Dhttps.proxyHost=fodev.org -Dhttps.proxyPort=8118
    - sudo cp "build/libs/Xtra Api-0.0.1-SNAPSHOT.jar" /var/xtra/api.jar
    - sudo systemctl restart xtra-api
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew check
  only:
    - deploy

after_script:
  - echo "End CI/CD"